---
name: docker-push-ghcr-use-host-ovs

on:
  push:
    branches: [main]
  workflow_run:
    types:
      - completed
    workflows:
      - 'automerge'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: metaci
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/ci/${{ github.event.repository.name }}-use-host-ovs
          tags: |
            type=ref,event=pr
            type=sha,prefix=

      - name: "Build and push for Dockerfile.use-host-ovs"
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.use-host-ovs
          context: .
          push: true
          tags: ${{ steps.metaci.outputs.tags }}
